/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  GDriveSyncPlugin: () => GDriveSyncPlugin,
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/googleDriveApi.ts
var import_obsidian = require("obsidian");
var FOLDER_MIME = "application/vnd.google-apps.folder";
var GoogleDriveApi = class _GoogleDriveApi {
  constructor(config, vaultName, remoteBaseDir, onConfigUpdate) {
    this.rootFolderId = null;
    this.pathToEntity = /* @__PURE__ */ new Map();
    this.folderPathToId = /* @__PURE__ */ new Map();
    this.config = config;
    this.vaultName = vaultName;
    this.remoteBaseDir = remoteBaseDir.trim() || vaultName;
    this.onConfigUpdate = onConfigUpdate;
  }
  updateConfig(newConfig, newBaseDir) {
    this.config = newConfig;
    if (newBaseDir !== void 0) {
      this.remoteBaseDir = newBaseDir.trim() || this.vaultName;
      this.clearCache();
    }
  }
  /**
   * Clears in-memory path and folder ID caches so stale IDs are never reused
   */
  clearCache() {
    this.rootFolderId = null;
    this.pathToEntity.clear();
    this.folderPathToId.clear();
  }
  static formatGoogleError(rawText, status) {
    try {
      const json = JSON.parse(rawText);
      const err = json.error;
      const code = typeof err === "string" ? err : err?.message || err?.status || "";
      const desc = json.error_description || (typeof err === "object" ? err?.message : "") || "";
      const full = `${code} ${desc}`;
      if (full.includes("invalid_grant")) {
        return "Google authorization expired or was revoked. Please reconnect your account in Settings.";
      }
      if (full.includes("invalid_client")) {
        return "Invalid Google Client ID or Client Secret. Please verify your credentials in Settings.";
      }
      if (full.includes("access_denied")) {
        return "Access denied on Google consent screen.";
      }
      if (full.includes("insufficientPermissions") || full.includes("ACCESS_TOKEN_SCOPE_INSUFFICIENT")) {
        return "Insufficient Google Drive permissions. Ensure the required scope ('https://www.googleapis.com/auth/drive' or 'https://www.googleapis.com/auth/drive.file') is added to your OAuth Consent Screen in Google Cloud Console.";
      }
      if (full.includes("rateLimitExceeded") || full.includes("userRateLimitExceeded")) {
        return "Google Drive API rate limit reached. Please wait a moment before syncing again.";
      }
      if (desc)
        return desc;
      if (err?.message)
        return err.message;
    } catch {
    }
    if (rawText.includes("invalid_grant")) {
      return "Google authorization expired or was revoked. Please reconnect your account in Settings.";
    }
    if (rawText.includes("invalid_client")) {
      return "Invalid Google Client ID or Client Secret. Please verify your credentials in Settings.";
    }
    return rawText || `HTTP ${status || "unknown error"}`;
  }
  /**
   * Retrieves a valid access token, automatically refreshing if needed
   */
  async getAccessToken() {
    if (!this.config.refreshToken) {
      throw new Error("Google Drive is not authenticated. Please log in first.");
    }
    const now = Date.now();
    if (this.config.accessToken && this.config.accessTokenExpiresAtMs > now + 12e4) {
      return this.config.accessToken;
    }
    const params = new URLSearchParams({
      client_id: this.config.clientId,
      grant_type: "refresh_token",
      refresh_token: this.config.refreshToken
    });
    if (this.config.clientSecret) {
      params.append("client_secret", this.config.clientSecret);
    }
    const resp = await (0, import_obsidian.requestUrl)({
      url: "https://oauth2.googleapis.com/token",
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: params.toString()
    });
    if (resp.status !== 200) {
      throw new Error(
        `Failed to refresh Google Drive access token: ${_GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`
      );
    }
    const data = resp.json;
    this.config.accessToken = data.access_token;
    const expiresIn = Number(data.expires_in) || 3600;
    this.config.accessTokenExpiresAtMs = now + expiresIn * 1e3;
    await this.onConfigUpdate(this.config);
    return this.config.accessToken;
  }
  /**
   * Fetches user profile (email and display name)
   */
  async getUserInfo() {
    const token = await this.getAccessToken();
    const resp = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/drive/v3/about?fields=user(displayName,emailAddress)",
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    if (resp.status !== 200) {
      throw new Error(`Failed to get Google account info: ${resp.text}`);
    }
    const user = resp.json.user || {};
    return {
      email: user.emailAddress || "",
      name: user.displayName || ""
    };
  }
  /**
   * Initializes or locates the remote root folder for this vault on Google Drive
   */
  async initRootFolder() {
    if (this.rootFolderId) {
      return this.rootFolderId;
    }
    let segments = this.remoteBaseDir.split("/").map((s) => s.trim()).filter((s) => s.length > 0);
    if (segments.length > 0 && (segments[0].toLowerCase() === "my drive" || segments[0].toLowerCase() === "mydrive")) {
      segments = segments.slice(1);
    }
    let parentId = "root";
    let cumulativePath = "";
    for (const segment of segments) {
      cumulativePath = cumulativePath ? `${cumulativePath}/${segment}` : segment;
      let folderId = this.folderPathToId.get(cumulativePath);
      if (!folderId) {
        folderId = await this.findOrCreateFolder(segment, parentId);
        this.folderPathToId.set(cumulativePath, folderId);
      }
      parentId = folderId;
    }
    this.rootFolderId = parentId;
    this.folderPathToId.set("", parentId);
    return this.rootFolderId;
  }
  async findOrCreateFolder(name, parentId) {
    const token = await this.getAccessToken();
    const query = `'${parentId}' in parents and name = '${name.replace(/'/g, "\\'")}' and mimeType = '${FOLDER_MIME}' and trashed = false`;
    const searchUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      query
    )}&fields=files(id,name)&pageSize=10`;
    const searchResp = await (0, import_obsidian.requestUrl)({
      url: searchUrl,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    if (searchResp.status === 200 && searchResp.json.files?.length > 0) {
      const sorted = searchResp.json.files.sort((a, b) => {
        const tA = a.modifiedTime ? Date.parse(a.modifiedTime) : 0;
        const tB = b.modifiedTime ? Date.parse(b.modifiedTime) : 0;
        return tB - tA;
      });
      return sorted[0].id;
    }
    const createResp = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/drive/v3/files",
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name,
        mimeType: FOLDER_MIME,
        parents: [parentId]
      })
    });
    if (createResp.status !== 200 && createResp.status !== 201) {
      throw new Error(`Failed to create remote folder "${name}": ${createResp.text}`);
    }
    return createResp.json.id;
  }
  /**
   * Recursively walks all files and folders inside the remote vault
   */
  async walk() {
    this.clearCache();
    const rootId = await this.initRootFolder();
    const allEntities = [];
    const queue = [
      { folderId: rootId, folderPath: "" }
    ];
    while (queue.length > 0) {
      const { folderId, folderPath } = queue.shift();
      let pageToken = void 0;
      do {
        const token = await this.getAccessToken();
        const query = `'${folderId}' in parents and trashed = false`;
        let url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
          query
        )}&pageSize=1000&fields=nextPageToken,files(id,name,mimeType,size,modifiedTime,createdTime,md5Checksum)`;
        if (pageToken) {
          url += `&pageToken=${encodeURIComponent(pageToken)}`;
        }
        const resp = await (0, import_obsidian.requestUrl)({
          url,
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`
          }
        });
        if (resp.status !== 200) {
          throw new Error(
            `Failed to list files in folder "${folderPath}": ${_GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`
          );
        }
        const files = resp.json.files || [];
        for (const file of files) {
          const isFolder = file.mimeType === FOLDER_MIME;
          const relativeKey = folderPath ? `${folderPath}/${file.name}` : file.name;
          const normalizedKey = isFolder ? `${relativeKey}/` : relativeKey;
          const entity = {
            key: normalizedKey,
            isFolder,
            size: isFolder ? 0 : Number(file.size) || 0,
            mtime: file.modifiedTime ? Date.parse(file.modifiedTime) : Date.now(),
            ctime: file.createdTime ? Date.parse(file.createdTime) : void 0,
            hash: file.md5Checksum,
            id: file.id,
            parentID: folderId
          };
          const existing = this.pathToEntity.get(normalizedKey);
          if (existing) {
            if (entity.mtime <= existing.mtime) {
              continue;
            }
            const idx = allEntities.findIndex((e) => e.key === normalizedKey);
            if (idx >= 0)
              allEntities.splice(idx, 1);
          }
          this.pathToEntity.set(normalizedKey, entity);
          allEntities.push(entity);
          if (isFolder) {
            this.folderPathToId.set(relativeKey, file.id);
            queue.push({ folderId: file.id, folderPath: relativeKey });
          }
        }
        pageToken = resp.json.nextPageToken;
      } while (pageToken);
    }
    return allEntities;
  }
  /**
   * Reads a file's binary content from Google Drive
   */
  async readFile(key) {
    const entity = this.pathToEntity.get(key);
    let fileId = entity?.id;
    if (!fileId) {
      const resolved = await this.lookupEntity(key);
      if (!resolved || !resolved.id) {
        throw new Error(`Remote file not found: ${key}`);
      }
      fileId = resolved.id;
    }
    const token = await this.getAccessToken();
    const resp = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    if (resp.status !== 200) {
      throw new Error(`Failed to download remote file "${key}": ${resp.status}`);
    }
    return resp.arrayBuffer;
  }
  /**
   * Uploads or updates a file on Google Drive
   */
  async writeFile(key, content, mtime) {
    await this.initRootFolder();
    const token = await this.getAccessToken();
    const existingEntity = this.pathToEntity.get(key) || await this.lookupEntity(key);
    const parentId = await this.ensureParentFolderExists(key);
    const fileName = key.split("/").pop();
    const metadata = {
      name: fileName
    };
    if (mtime) {
      metadata.modifiedTime = new Date(mtime).toISOString();
    }
    let resultFile;
    if (content.byteLength <= 5 * 1024 * 1024) {
      resultFile = await this.uploadMultipart(
        token,
        existingEntity?.id,
        parentId,
        metadata,
        content
      );
    } else {
      resultFile = await this.uploadResumable(
        token,
        existingEntity?.id,
        parentId,
        metadata,
        content
      );
    }
    const entity = {
      key,
      isFolder: false,
      size: Number(resultFile.size) || content.byteLength,
      mtime: resultFile.modifiedTime ? Date.parse(resultFile.modifiedTime) : mtime || Date.now(),
      ctime: resultFile.createdTime ? Date.parse(resultFile.createdTime) : void 0,
      hash: resultFile.md5Checksum,
      id: resultFile.id,
      parentID: parentId
    };
    this.pathToEntity.set(key, entity);
    return entity;
  }
  /**
   * Creates a directory on Google Drive
   */
  async mkdir(key) {
    await this.initRootFolder();
    const cleanKey = key.replace(/\/+$/, "");
    const existing = this.pathToEntity.get(`${cleanKey}/`);
    if (existing) {
      return existing;
    }
    const parentId = await this.ensureParentFolderExists(cleanKey);
    const folderName = cleanKey.split("/").pop();
    const token = await this.getAccessToken();
    const resp = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/drive/v3/files?fields=id,name,mimeType,modifiedTime,createdTime",
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name: folderName,
        mimeType: FOLDER_MIME,
        parents: [parentId]
      })
    });
    if (resp.status !== 200 && resp.status !== 201) {
      throw new Error(`Failed to create remote folder "${cleanKey}": ${resp.text}`);
    }
    const folderId = resp.json.id;
    this.folderPathToId.set(cleanKey, folderId);
    const entity = {
      key: `${cleanKey}/`,
      isFolder: true,
      size: 0,
      mtime: resp.json.modifiedTime ? Date.parse(resp.json.modifiedTime) : Date.now(),
      ctime: resp.json.createdTime ? Date.parse(resp.json.createdTime) : void 0,
      id: folderId,
      parentID: parentId
    };
    this.pathToEntity.set(`${cleanKey}/`, entity);
    return entity;
  }
  /**
   * Checks if a remote Google Drive folder is completely empty (no non-trashed children)
   */
  async isFolderEmpty(key) {
    const entity = this.pathToEntity.get(key) || await this.lookupEntity(key);
    if (!entity || !entity.id) {
      return true;
    }
    const token = await this.getAccessToken();
    const query = `'${entity.id}' in parents and trashed = false`;
    const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      query
    )}&pageSize=1&fields=files(id)`;
    const resp = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    if (resp.status === 200 && resp.json.files) {
      return resp.json.files.length === 0;
    }
    return true;
  }
  /**
   * Deletes (or trashes) a file or folder on Google Drive ONLY if folder is empty
   */
  async rm(key, permanent = false) {
    const entity = this.pathToEntity.get(key) || await this.lookupEntity(key);
    if (!entity || !entity.id) {
      return true;
    }
    if (key.endsWith("/")) {
      const empty = await this.isFolderEmpty(key);
      if (!empty) {
        console.warn(
          `Skipped deleting remote folder "${key}" because it still contains active files on Google Drive.`
        );
        return false;
      }
    }
    const token = await this.getAccessToken();
    if (permanent) {
      const resp = await (0, import_obsidian.requestUrl)({
        url: `https://www.googleapis.com/drive/v3/files/${entity.id}`,
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (resp.status !== 200 && resp.status !== 204) {
        throw new Error(
          `Failed to permanently delete "${key}": ${_GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`
        );
      }
    } else {
      const resp = await (0, import_obsidian.requestUrl)({
        url: `https://www.googleapis.com/drive/v3/files/${entity.id}`,
        method: "PATCH",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ trashed: true })
      });
      if (resp.status !== 200) {
        throw new Error(
          `Failed to trash "${key}": ${_GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`
        );
      }
    }
    this.pathToEntity.delete(key);
    const cleanKey = key.replace(/\/+$/, "");
    this.folderPathToId.delete(cleanKey);
    return true;
  }
  async ensureParentFolderExists(childKey) {
    const clean = childKey.replace(/\/+$/, "");
    const parts = clean.split("/");
    parts.pop();
    if (parts.length === 0) {
      return await this.initRootFolder();
    }
    let currentParentId = await this.initRootFolder();
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      let folderId = this.folderPathToId.get(currentPath);
      if (!folderId) {
        folderId = await this.findOrCreateFolder(part, currentParentId);
        this.folderPathToId.set(currentPath, folderId);
        this.pathToEntity.set(`${currentPath}/`, {
          key: `${currentPath}/`,
          isFolder: true,
          size: 0,
          mtime: Date.now(),
          id: folderId,
          parentID: currentParentId
        });
      }
      currentParentId = folderId;
    }
    return currentParentId;
  }
  async uploadMultipart(token, existingId, parentId, metadata, content) {
    const boundary = "-------GDRIVE_SYNC_" + Math.random().toString(36).substring(2);
    const delimiter = `\r
--${boundary}\r
`;
    const closeDelimiter = `\r
--${boundary}--`;
    if (!existingId) {
      metadata.parents = [parentId];
    }
    const metaPart = "Content-Type: application/json; charset=UTF-8\r\n\r\n" + JSON.stringify(metadata) + delimiter + "Content-Type: application/octet-stream\r\n\r\n";
    const encoder = new TextEncoder();
    const metaBytes = encoder.encode(delimiter + metaPart);
    const closeBytes = encoder.encode(closeDelimiter);
    const combined = new Uint8Array(
      metaBytes.byteLength + content.byteLength + closeBytes.byteLength
    );
    combined.set(metaBytes, 0);
    combined.set(new Uint8Array(content), metaBytes.byteLength);
    combined.set(closeBytes, metaBytes.byteLength + content.byteLength);
    const isUpdate = !!existingId;
    const url = isUpdate ? `https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=multipart&fields=id,name,mimeType,size,modifiedTime,createdTime,md5Checksum` : "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,modifiedTime,createdTime,md5Checksum";
    const resp = await (0, import_obsidian.requestUrl)({
      url,
      method: isUpdate ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary=${boundary}`
      },
      body: combined.buffer
    });
    if (resp.status !== 200 && resp.status !== 201) {
      throw new Error(`Multipart upload failed: ${resp.text}`);
    }
    return resp.json;
  }
  async uploadResumable(token, existingId, parentId, metadata, content) {
    if (!existingId) {
      metadata.parents = [parentId];
    }
    const isUpdate = !!existingId;
    const startUrl = isUpdate ? `https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=resumable&fields=id,name,mimeType,size,modifiedTime,createdTime,md5Checksum` : "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,mimeType,size,modifiedTime,createdTime,md5Checksum";
    const initResp = await (0, import_obsidian.requestUrl)({
      url: startUrl,
      method: isUpdate ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": "application/octet-stream",
        "X-Upload-Content-Length": `${content.byteLength}`
      },
      body: JSON.stringify(metadata)
    });
    if (initResp.status !== 200 && initResp.status !== 201) {
      throw new Error(`Resumable upload initialization failed: ${initResp.text}`);
    }
    const uploadUrl = initResp.headers["location"] || initResp.headers["Location"];
    if (!uploadUrl) {
      throw new Error("No upload Location header returned by Google Drive");
    }
    const chunkSize = 5 * 1024 * 1024;
    let offset = 0;
    const totalBytes = content.byteLength;
    let lastResult = null;
    while (offset < totalBytes) {
      const end = Math.min(offset + chunkSize, totalBytes);
      const chunk = content.slice(offset, end);
      const contentRange = `bytes ${offset}-${end - 1}/${totalBytes}`;
      const chunkResp = await (0, import_obsidian.requestUrl)({
        url: uploadUrl,
        method: "PUT",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Length": `${chunk.byteLength}`,
          "Content-Range": contentRange
        },
        body: chunk
      });
      if (chunkResp.status === 200 || chunkResp.status === 201) {
        lastResult = chunkResp.json;
        break;
      } else if (chunkResp.status === 308) {
        offset = end;
      } else {
        throw new Error(
          `Chunk upload failed at offset ${offset}: ${chunkResp.status} ${chunkResp.text}`
        );
      }
    }
    if (!lastResult) {
      throw new Error("Resumable upload did not complete with file metadata");
    }
    return lastResult;
  }
  async lookupEntity(key) {
    const isFolder = key.endsWith("/");
    const cleanKey = key.replace(/\/+$/, "");
    const parts = cleanKey.split("/");
    const fileName = parts[parts.length - 1];
    const parentId = await this.ensureParentFolderExists(cleanKey);
    const token = await this.getAccessToken();
    const query = `'${parentId}' in parents and name = '${fileName.replace(
      /'/g,
      "\\'"
    )}' and trashed = false`;
    const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      query
    )}&fields=files(id,name,mimeType,size,modifiedTime,createdTime,md5Checksum)`;
    const resp = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    if (resp.status === 200 && resp.json.files?.length > 0) {
      const sorted = resp.json.files.sort((a, b) => {
        const tA = a.modifiedTime ? Date.parse(a.modifiedTime) : 0;
        const tB = b.modifiedTime ? Date.parse(b.modifiedTime) : 0;
        return tB - tA;
      });
      const file = sorted[0];
      const entity = {
        key,
        isFolder: file.mimeType === FOLDER_MIME,
        size: Number(file.size) || 0,
        mtime: file.modifiedTime ? Date.parse(file.modifiedTime) : Date.now(),
        ctime: file.createdTime ? Date.parse(file.createdTime) : void 0,
        hash: file.md5Checksum,
        id: file.id,
        parentID: parentId
      };
      this.pathToEntity.set(key, entity);
      return entity;
    }
    return null;
  }
};

// src/localFs.ts
var import_obsidian2 = require("obsidian");
var FsLocal = class {
  constructor(vault, syncConfigDir = false, ignoredPatternStrings = []) {
    this.vault = vault;
    this.syncConfigDir = syncConfigDir;
    this.ignoredPatterns = ignoredPatternStrings.map((pattern) => {
      try {
        return new RegExp(pattern);
      } catch (e) {
        console.error(`Invalid ignore pattern: ${pattern}`, e);
        return null;
      }
    }).filter((r) => r !== null);
  }
  /**
   * Check whether a path should be ignored from syncing
   */
  isIgnored(path) {
    const normalized = (0, import_obsidian2.normalizePath)(path);
    const configDir = this.vault.configDir || ".obsidian";
    if (!this.syncConfigDir && (normalized === configDir || normalized.startsWith(`${configDir}/`))) {
      return true;
    }
    if (normalized.includes("obsidian-gdrive-sync")) {
      return true;
    }
    for (const re of this.ignoredPatterns) {
      if (re.test(normalized)) {
        return true;
      }
    }
    return false;
  }
  /**
   * Recursively walks the local vault and gathers all files and folders
   */
  async walk() {
    const results = [];
    const queue = [""];
    while (queue.length > 0) {
      const currentFolder = queue.shift();
      let listed;
      try {
        listed = await this.vault.adapter.list(currentFolder);
      } catch (err) {
        console.warn(`Failed to list folder: "${currentFolder}"`, err);
        continue;
      }
      for (const folderPath of listed.folders) {
        const normalized = (0, import_obsidian2.normalizePath)(folderPath);
        if (this.isIgnored(normalized)) {
          continue;
        }
        const stat = await this.vault.adapter.stat(normalized);
        const keyWithSlash = normalized.endsWith("/") ? normalized : `${normalized}/`;
        results.push({
          key: keyWithSlash,
          isFolder: true,
          size: 0,
          mtime: stat?.mtime ?? Date.now(),
          ctime: stat?.ctime
        });
        queue.push(normalized);
      }
      for (const filePath of listed.files) {
        const normalized = (0, import_obsidian2.normalizePath)(filePath);
        if (this.isIgnored(normalized)) {
          continue;
        }
        const stat = await this.vault.adapter.stat(normalized);
        if (!stat)
          continue;
        results.push({
          key: normalized,
          isFolder: false,
          size: stat.size,
          mtime: stat.mtime,
          ctime: stat.ctime
        });
      }
    }
    return results;
  }
  /**
   * Reads a file as binary ArrayBuffer
   */
  async readFile(key) {
    const normalized = (0, import_obsidian2.normalizePath)(key);
    return await this.vault.adapter.readBinary(normalized);
  }
  /**
   * Writes binary data using Obsidian's Vault API (notifies active editor tabs to avoid overwrites)
   */
  async writeFile(key, data) {
    const normalized = (0, import_obsidian2.normalizePath)(key);
    const parentFolder = this.getParentPath(normalized);
    if (parentFolder && !await this.vault.adapter.exists(parentFolder)) {
      await this.vault.adapter.mkdir(parentFolder);
    }
    const abstractFile = this.vault.getAbstractFileByPath(normalized);
    if (abstractFile instanceof import_obsidian2.TFile) {
      await this.vault.modifyBinary(abstractFile, data);
    } else {
      await this.vault.createBinary(normalized, data);
    }
  }
  /**
   * Creates a directory if it does not already exist
   */
  async mkdir(key) {
    const normalized = (0, import_obsidian2.normalizePath)(key.replace(/\/+$/, ""));
    if (!normalized)
      return;
    if (!await this.vault.adapter.exists(normalized)) {
      await this.vault.adapter.mkdir(normalized);
    }
  }
  /**
   * Deletes a file safely via Obsidian's Vault API
   */
  async deleteFile(key) {
    const normalized = (0, import_obsidian2.normalizePath)(key);
    const file = this.vault.getAbstractFileByPath(normalized);
    if (file instanceof import_obsidian2.TFile) {
      try {
        await this.vault.trash(file, true);
      } catch {
        await this.vault.adapter.remove(normalized);
      }
    } else if (await this.vault.adapter.exists(normalized)) {
      try {
        await this.vault.adapter.trashLocal(normalized);
      } catch {
        await this.vault.adapter.remove(normalized);
      }
    }
  }
  /**
   * Checks if a folder has zero files and zero subfolders
   */
  async isFolderEmpty(key) {
    const normalized = (0, import_obsidian2.normalizePath)(key.replace(/\/+$/, ""));
    if (!normalized || !await this.vault.adapter.exists(normalized)) {
      return true;
    }
    const listing = await this.vault.adapter.list(normalized);
    return listing.files.length === 0 && listing.folders.length === 0;
  }
  /**
   * Deletes a folder ONLY if it is completely empty
   */
  async deleteFolder(key) {
    const normalized = (0, import_obsidian2.normalizePath)(key.replace(/\/+$/, ""));
    if (!normalized)
      return false;
    if (!await this.isFolderEmpty(normalized)) {
      console.warn(
        `Skipped deleting local folder "${normalized}" because it is not empty.`
      );
      return false;
    }
    const folder = this.vault.getAbstractFileByPath(normalized);
    if (folder instanceof import_obsidian2.TFolder) {
      try {
        await this.vault.trash(folder, true);
        return true;
      } catch {
        await this.vault.adapter.rmdir(normalized, false);
        return true;
      }
    } else if (await this.vault.adapter.exists(normalized)) {
      await this.vault.adapter.rmdir(normalized, false);
      return true;
    }
    return false;
  }
  /**
   * Gets stats of a file or folder
   */
  async stat(key) {
    const isFolder = key.endsWith("/");
    const normalized = (0, import_obsidian2.normalizePath)(key.replace(/\/+$/, ""));
    const stat = await this.vault.adapter.stat(normalized);
    if (!stat)
      return null;
    return {
      key: isFolder ? `${normalized}/` : normalized,
      isFolder: stat.type === "folder",
      size: stat.size,
      mtime: stat.mtime,
      ctime: stat.ctime
    };
  }
  getParentPath(path) {
    const parts = path.split("/");
    parts.pop();
    return parts.join("/");
  }
};

// src/localDb.ts
var LocalDb = class {
  constructor(plugin) {
    this.records = /* @__PURE__ */ new Map();
    this.isLoaded = false;
    this.plugin = plugin;
  }
  async load() {
    if (this.isLoaded)
      return;
    try {
      const data = await this.plugin.loadData();
      if (data && data.syncRecords) {
        this.records.clear();
        for (const [key, raw] of Object.entries(
          data.syncRecords
        )) {
          const record = {
            key: raw.key,
            isFolder: raw.isFolder,
            localSize: raw.localSize ?? raw.size ?? 0,
            localMtime: raw.localMtime ?? raw.mtime ?? 0,
            remoteHash: raw.remoteHash ?? raw.hash,
            remoteMtime: raw.remoteMtime ?? raw.mtime,
            remoteSize: raw.remoteSize ?? raw.size,
            syncTime: raw.syncTime ?? 0
          };
          this.records.set(key, record);
        }
      }
    } catch (err) {
      console.warn("Failed to load sync records from local database", err);
    }
    this.isLoaded = true;
  }
  async save() {
    try {
      const currentData = await this.plugin.loadData() || {};
      const recordsObj = {};
      for (const [key, record] of this.records.entries()) {
        recordsObj[key] = record;
      }
      currentData.syncRecords = recordsObj;
      await this.plugin.saveData(currentData);
    } catch (err) {
      console.error("Failed to save sync records to local database", err);
    }
  }
  getRecord(key) {
    return this.records.get(key);
  }
  getAllRecords() {
    return new Map(this.records);
  }
  upsertRecord(record) {
    this.records.set(record.key, record);
  }
  deleteRecord(key) {
    this.records.delete(key);
  }
  clear() {
    this.records.clear();
  }
  get count() {
    return this.records.size;
  }
};

// src/md5.ts
function safeAdd(x, y) {
  const lsw = (x & 65535) + (y & 65535);
  const msw = (x >> 16) + (y >> 16) + (lsw >> 16);
  return msw << 16 | lsw & 65535;
}
function bitRotateLeft(num, cnt) {
  return num << cnt | num >>> 32 - cnt;
}
function md5cmn(q, a, b, x, s, t) {
  return safeAdd(bitRotateLeft(safeAdd(safeAdd(a, q), safeAdd(x, t)), s), b);
}
function md5ff(a, b, c, d, x, s, t) {
  return md5cmn(b & c | ~b & d, a, b, x, s, t);
}
function md5gg(a, b, c, d, x, s, t) {
  return md5cmn(b & d | c & ~d, a, b, x, s, t);
}
function md5hh(a, b, c, d, x, s, t) {
  return md5cmn(b ^ c ^ d, a, b, x, s, t);
}
function md5ii(a, b, c, d, x, s, t) {
  return md5cmn(c ^ (b | ~d), a, b, x, s, t);
}
function md5(buffer) {
  const bytes = new Uint8Array(buffer);
  const len = bytes.length;
  const nWords = (len + 8 >> 6) + 1;
  const words = new Int32Array(nWords * 16);
  for (let i = 0; i < len; i++) {
    words[i >> 2] |= bytes[i] << i % 4 * 8;
  }
  words[len >> 2] |= 128 << len % 4 * 8;
  words[nWords * 16 - 2] = len * 8;
  let a = 1732584193;
  let b = -271733879;
  let c = -1732584194;
  let d = 271733878;
  for (let i = 0; i < words.length; i += 16) {
    const olda = a;
    const oldb = b;
    const oldc = c;
    const oldd = d;
    a = md5ff(a, b, c, d, words[i], 7, -680876936);
    d = md5ff(d, a, b, c, words[i + 1], 12, -389564586);
    c = md5ff(c, d, a, b, words[i + 2], 17, 606105819);
    b = md5ff(b, c, d, a, words[i + 3], 22, -1044525330);
    a = md5ff(a, b, c, d, words[i + 4], 7, -176418897);
    d = md5ff(d, a, b, c, words[i + 5], 12, 1200080426);
    c = md5ff(c, d, a, b, words[i + 6], 17, -1473231341);
    b = md5ff(b, c, d, a, words[i + 7], 22, -45705983);
    a = md5ff(a, b, c, d, words[i + 8], 7, 1770035416);
    d = md5ff(d, a, b, c, words[i + 9], 12, -1958414417);
    c = md5ff(c, d, a, b, words[i + 10], 17, -42063);
    b = md5ff(b, c, d, a, words[i + 11], 22, -1990404162);
    a = md5ff(a, b, c, d, words[i + 12], 7, 1804603682);
    d = md5ff(d, a, b, c, words[i + 13], 12, -40341101);
    c = md5ff(c, d, a, b, words[i + 14], 17, -1502002290);
    b = md5ff(b, c, d, a, words[i + 15], 22, 1236535329);
    a = md5gg(a, b, c, d, words[i + 1], 5, -165796510);
    d = md5gg(d, a, b, c, words[i + 6], 9, -1069501632);
    c = md5gg(c, d, a, b, words[i + 11], 14, 643717713);
    b = md5gg(b, c, d, a, words[i], 20, -373897302);
    a = md5gg(a, b, c, d, words[i + 5], 5, -701558691);
    d = md5gg(d, a, b, c, words[i + 10], 9, 38016083);
    c = md5gg(c, d, a, b, words[i + 15], 14, -660478335);
    b = md5gg(b, c, d, a, words[i + 4], 20, -405537848);
    a = md5gg(a, b, c, d, words[i + 9], 5, 568446438);
    d = md5gg(d, a, b, c, words[i + 14], 9, -1019803690);
    c = md5gg(c, d, a, b, words[i + 3], 14, -187363961);
    b = md5gg(b, c, d, a, words[i + 8], 20, 1163531501);
    a = md5gg(a, b, c, d, words[i + 13], 5, -1444681467);
    d = md5gg(d, a, b, c, words[i + 2], 9, -51403784);
    c = md5gg(c, d, a, b, words[i + 7], 14, 1735328473);
    b = md5gg(b, c, d, a, words[i + 12], 20, -1926607734);
    a = md5hh(a, b, c, d, words[i + 5], 4, -378558);
    d = md5hh(d, a, b, c, words[i + 8], 11, -2022574463);
    c = md5hh(c, d, a, b, words[i + 11], 16, 1839030562);
    b = md5hh(b, c, d, a, words[i + 14], 23, -35309556);
    a = md5hh(a, b, c, d, words[i + 1], 4, -1530992060);
    d = md5hh(d, a, b, c, words[i + 4], 11, 1272893353);
    c = md5hh(c, d, a, b, words[i + 7], 16, -155497632);
    b = md5hh(b, c, d, a, words[i + 10], 23, -1094730640);
    a = md5hh(a, b, c, d, words[i + 13], 4, 681279174);
    d = md5hh(d, a, b, c, words[i], 11, -358537222);
    c = md5hh(c, d, a, b, words[i + 3], 16, -722521979);
    b = md5hh(b, c, d, a, words[i + 6], 23, 76029189);
    a = md5hh(a, b, c, d, words[i + 9], 4, -640364487);
    d = md5hh(d, a, b, c, words[i + 12], 11, -421815835);
    c = md5hh(c, d, a, b, words[i + 15], 16, 530742520);
    b = md5hh(b, c, d, a, words[i + 2], 23, -995338651);
    a = md5ii(a, b, c, d, words[i], 6, -198630844);
    d = md5ii(d, a, b, c, words[i + 7], 10, 1126891415);
    c = md5ii(c, d, a, b, words[i + 14], 15, -1416354905);
    b = md5ii(b, c, d, a, words[i + 5], 21, -57434055);
    a = md5ii(a, b, c, d, words[i + 12], 6, 1700485571);
    d = md5ii(d, a, b, c, words[i + 3], 10, -1894986606);
    c = md5ii(c, d, a, b, words[i + 10], 15, -1051523);
    b = md5ii(b, c, d, a, words[i + 1], 21, -2054922799);
    a = md5ii(a, b, c, d, words[i + 8], 6, 1873313359);
    d = md5ii(d, a, b, c, words[i + 15], 10, -30611744);
    c = md5ii(c, d, a, b, words[i + 6], 15, -1560198380);
    b = md5ii(b, c, d, a, words[i + 13], 21, 1309151649);
    a = md5ii(a, b, c, d, words[i + 4], 6, -145523070);
    d = md5ii(d, a, b, c, words[i + 11], 10, -1120210379);
    c = md5ii(c, d, a, b, words[i + 2], 15, 718787259);
    b = md5ii(b, c, d, a, words[i + 9], 21, -343485551);
    a = safeAdd(a, olda);
    b = safeAdd(b, oldb);
    c = safeAdd(c, oldc);
    d = safeAdd(d, oldd);
  }
  const hexChars = "0123456789abcdef";
  let output = "";
  const resultWords = [a, b, c, d];
  for (let i = 0; i < 4; i++) {
    const word = resultWords[i];
    for (let j = 0; j < 4; j++) {
      const byte = word >> j * 8 & 255;
      output += hexChars.charAt(byte >> 4 & 15) + hexChars.charAt(byte & 15);
    }
  }
  return output;
}

// src/syncEngine.ts
var SyncEngine = class {
  constructor(localFs, driveApi, db, settings) {
    this.localFs = localFs;
    this.driveApi = driveApi;
    this.db = db;
    this.settings = settings;
  }
  /**
   * Plans the synchronization actions by comparing local, remote, and previous sync state
   */
  async planSync(localEntities, remoteEntities) {
    const localMap = /* @__PURE__ */ new Map();
    for (const e of localEntities)
      localMap.set(e.key, e);
    const remoteMap = /* @__PURE__ */ new Map();
    for (const e of remoteEntities)
      remoteMap.set(e.key, e);
    const prevMap = this.db.getAllRecords();
    const allKeys = /* @__PURE__ */ new Set([
      ...localMap.keys(),
      ...remoteMap.keys(),
      ...prevMap.keys()
    ]);
    const decisions = [];
    for (const key of allKeys) {
      if (this.localFs.isIgnored(key)) {
        continue;
      }
      const local = localMap.get(key);
      const remote = remoteMap.get(key);
      const prev = prevMap.get(key);
      const isFolder = key.endsWith("/");
      if (!isFolder && !prev && local && remote && local.size === remote.size && remote.hash && !local.hash) {
        try {
          const content = await this.localFs.readFile(key);
          local.hash = md5(content);
        } catch (err) {
          console.warn(`Could not compute MD5 for local file "${key}":`, err);
        }
      }
      const decision = this.decideItem(
        key,
        isFolder,
        local,
        remote,
        prev,
        this.settings.syncDirection,
        this.settings.conflictAction
      );
      decisions.push(decision);
    }
    for (const d of decisions) {
      if (d.isFolder && (d.action === "delete_local_folder" || d.action === "delete_remote_folder")) {
        const folderKey = d.key;
        const hasActiveChildren = decisions.some((child) => {
          if (child.key === folderKey || !child.key.startsWith(folderKey)) {
            return false;
          }
          const isChildDeletion = child.action === "delete_local" || child.action === "delete_remote" || child.action === "delete_local_folder" || child.action === "delete_remote_folder" || child.action === "skip";
          return !isChildDeletion;
        });
        if (hasActiveChildren) {
          if (d.action === "delete_local_folder") {
            d.action = d.remoteEntity ? "equal" : "create_remote_folder";
            d.isChange = !d.remoteEntity;
            d.reason = "Folder deletion cancelled: folder contains active or modified notes";
          } else if (d.action === "delete_remote_folder") {
            d.action = d.localEntity ? "equal" : "create_local_folder";
            d.isChange = !d.localEntity;
            d.reason = "Folder deletion cancelled: folder contains active or modified notes";
          }
        }
      }
    }
    return decisions;
  }
  decideItem(key, isFolder, local, remote, prev, direction = "bidirectional", conflictAction = "keep_newer") {
    if (isFolder) {
      return this.decideFolder(key, local, remote, prev, direction);
    }
    return this.decideFile(key, local, remote, prev, direction, conflictAction);
  }
  decideFolder(key, local, remote, prev, direction = "bidirectional") {
    if (local && remote) {
      return {
        key,
        isFolder: true,
        action: "equal",
        reason: "Folder exists locally and remotely",
        isChange: false
      };
    }
    if (local && !remote) {
      if (prev) {
        if (direction === "push_only") {
          return { key, isFolder: true, action: "skip", reason: "Remote folder deleted; push only skips", isChange: false };
        }
        return {
          key,
          isFolder: true,
          action: "delete_local_folder",
          localEntity: local,
          prevRecord: prev,
          reason: "Folder was deleted on Google Drive",
          isChange: true
        };
      } else {
        if (direction === "pull_only") {
          return { key, isFolder: true, action: "skip", reason: "Local folder created; pull only skips", isChange: false };
        }
        return {
          key,
          isFolder: true,
          action: "create_remote_folder",
          localEntity: local,
          reason: "Folder created locally",
          isChange: true
        };
      }
    }
    if (!local && remote) {
      if (prev) {
        if (direction === "pull_only") {
          return { key, isFolder: true, action: "skip", reason: "Local folder deleted; pull only skips", isChange: false };
        }
        return {
          key,
          isFolder: true,
          action: "delete_remote_folder",
          remoteEntity: remote,
          prevRecord: prev,
          reason: "Folder was deleted locally",
          isChange: true
        };
      } else {
        if (direction === "push_only") {
          return { key, isFolder: true, action: "skip", reason: "Remote folder created; push only skips", isChange: false };
        }
        return {
          key,
          isFolder: true,
          action: "create_local_folder",
          remoteEntity: remote,
          reason: "Folder created on Google Drive",
          isChange: true
        };
      }
    }
    return {
      key,
      isFolder: true,
      action: "skip",
      reason: "Folder no longer exists",
      isChange: false
    };
  }
  decideFile(key, local, remote, prev, direction = "bidirectional", conflictAction = "keep_newer") {
    if (local && remote) {
      const localUnchanged = prev && local.size === prev.localSize && Math.abs(local.mtime - prev.localMtime) <= 1500;
      const remoteUnchanged = prev && (prev.remoteHash && remote.hash ? remote.hash === prev.remoteHash : remote.size === prev.remoteSize && Math.abs(remote.mtime - (prev.remoteMtime ?? 0)) <= 1500);
      if (prev && localUnchanged && remoteUnchanged) {
        return {
          key,
          isFolder: false,
          action: "equal",
          localEntity: local,
          remoteEntity: remote,
          prevRecord: prev,
          reason: "Neither local nor remote file has changed since last sync",
          isChange: false
        };
      }
      const isIdentical = local.size === remote.size && (local.hash && remote.hash && local.hash === remote.hash || Math.abs(local.mtime - remote.mtime) <= 1500);
      if (isIdentical) {
        return {
          key,
          isFolder: false,
          action: "equal",
          localEntity: local,
          remoteEntity: remote,
          prevRecord: prev,
          reason: "File is identical on both sides",
          isChange: false
        };
      }
      if (localUnchanged && !remoteUnchanged) {
        if (direction === "push_only") {
          return { key, isFolder: false, action: "skip", reason: "Remote modified; push only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "download",
          localEntity: local,
          remoteEntity: remote,
          prevRecord: prev,
          reason: "Remote file was modified",
          isChange: true
        };
      }
      if (!localUnchanged && remoteUnchanged) {
        if (direction === "pull_only") {
          return { key, isFolder: false, action: "skip", reason: "Local modified; pull only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "upload",
          localEntity: local,
          remoteEntity: remote,
          prevRecord: prev,
          reason: "Local file was modified",
          isChange: true
        };
      }
      if (direction === "push_only") {
        return {
          key,
          isFolder: false,
          action: "upload",
          localEntity: local,
          remoteEntity: remote,
          reason: "Push only mode overrides remote conflict",
          isChange: true
        };
      }
      if (direction === "pull_only") {
        return {
          key,
          isFolder: false,
          action: "download",
          localEntity: local,
          remoteEntity: remote,
          reason: "Pull only mode overrides local conflict",
          isChange: true
        };
      }
      switch (conflictAction) {
        case "keep_remote":
          return {
            key,
            isFolder: false,
            action: "conflict_keep_remote",
            localEntity: local,
            remoteEntity: remote,
            reason: "Conflict: keep remote selected",
            isChange: true
          };
        case "keep_local":
          return {
            key,
            isFolder: false,
            action: "conflict_keep_local",
            localEntity: local,
            remoteEntity: remote,
            reason: "Conflict: keep local selected",
            isChange: true
          };
        case "create_conflict_copy":
          return {
            key,
            isFolder: false,
            action: "conflict_create_copy",
            localEntity: local,
            remoteEntity: remote,
            reason: "Conflict: creating conflict copy",
            isChange: true
          };
        case "keep_newer":
        default:
          if (local.mtime >= remote.mtime) {
            return {
              key,
              isFolder: false,
              action: "conflict_keep_newer",
              localEntity: local,
              remoteEntity: remote,
              reason: "Conflict: local is newer",
              isChange: true
            };
          } else {
            return {
              key,
              isFolder: false,
              action: "conflict_keep_newer",
              localEntity: local,
              remoteEntity: remote,
              reason: "Conflict: remote is newer",
              isChange: true
            };
          }
      }
    }
    if (local && !remote) {
      if (prev) {
        const localModifiedSincePrev = local.size !== prev.localSize || Math.abs(local.mtime - prev.localMtime) > 1500;
        if (localModifiedSincePrev) {
          if (direction === "pull_only") {
            return { key, isFolder: false, action: "skip", reason: "Local modified but remote deleted; pull only skips", isChange: false };
          }
          return {
            key,
            isFolder: false,
            action: "upload",
            localEntity: local,
            prevRecord: prev,
            reason: "Local file was modified after remote deletion (edit wins over delete)",
            isChange: true
          };
        }
        if (direction === "push_only") {
          return { key, isFolder: false, action: "skip", reason: "Deleted remotely; push only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "delete_local",
          localEntity: local,
          prevRecord: prev,
          reason: "File was deleted on Google Drive",
          isChange: true
        };
      } else {
        if (direction === "pull_only") {
          return { key, isFolder: false, action: "skip", reason: "Created locally; pull only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "upload",
          localEntity: local,
          reason: "New local file",
          isChange: true
        };
      }
    }
    if (!local && remote) {
      if (prev) {
        const remoteModifiedSincePrev = prev.remoteHash && remote.hash ? remote.hash !== prev.remoteHash : remote.size !== prev.remoteSize || Math.abs(remote.mtime - (prev.remoteMtime ?? 0)) > 1500;
        if (remoteModifiedSincePrev) {
          if (direction === "push_only") {
            return { key, isFolder: false, action: "skip", reason: "Remote modified but local deleted; push only skips", isChange: false };
          }
          return {
            key,
            isFolder: false,
            action: "download",
            remoteEntity: remote,
            prevRecord: prev,
            reason: "Remote file was modified after local deletion (edit wins over delete)",
            isChange: true
          };
        }
        if (direction === "pull_only") {
          return { key, isFolder: false, action: "skip", reason: "Deleted locally; pull only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "delete_remote",
          remoteEntity: remote,
          prevRecord: prev,
          reason: "File was deleted locally",
          isChange: true
        };
      } else {
        if (direction === "push_only") {
          return { key, isFolder: false, action: "skip", reason: "Created remotely; push only skips", isChange: false };
        }
        return {
          key,
          isFolder: false,
          action: "download",
          remoteEntity: remote,
          reason: "New file on Google Drive",
          isChange: true
        };
      }
    }
    return {
      key,
      isFolder: false,
      action: "skip",
      reason: "File removed from both sides",
      isChange: false
    };
  }
  /**
   * Executes the synchronized plan
   */
  async executePlan(decisions, onProgress) {
    this.checkSafetyGuard(decisions);
    const errors = [];
    let syncedCount = 0;
    const now = Date.now();
    for (const d of decisions) {
      if (d.action === "equal") {
        const existing = this.db.getRecord(d.key);
        if (!existing) {
          this.db.upsertRecord({
            key: d.key,
            isFolder: d.isFolder,
            localSize: d.localEntity?.size ?? 0,
            localMtime: d.localEntity?.mtime ?? now,
            remoteHash: d.remoteEntity?.hash,
            remoteMtime: d.remoteEntity?.mtime,
            remoteSize: d.remoteEntity?.size,
            syncTime: now
          });
        }
      }
    }
    await this.db.save();
    const activeChanges = decisions.filter((d) => d.isChange);
    const totalCount = activeChanges.length;
    const folderCreations = activeChanges.filter(
      (d) => d.action === "create_local_folder" || d.action === "create_remote_folder"
    );
    folderCreations.sort((a, b) => a.key.length - b.key.length);
    for (const d of folderCreations) {
      try {
        if (d.action === "create_local_folder") {
          await this.localFs.mkdir(d.key);
        } else if (d.action === "create_remote_folder") {
          await this.driveApi.mkdir(d.key);
        }
        this.db.upsertRecord({
          key: d.key,
          isFolder: true,
          localSize: 0,
          localMtime: Date.now(),
          remoteMtime: Date.now(),
          remoteSize: 0,
          syncTime: Date.now()
        });
        syncedCount++;
        onProgress?.(syncedCount, totalCount, `Created folder: ${d.key}`, d.key);
      } catch (err) {
        errors.push({ key: d.key, error: err.message || String(err) });
      }
    }
    if (folderCreations.length > 0) {
      await this.db.save();
    }
    const fileOperations = activeChanges.filter(
      (d) => !d.isFolder && d.action !== "delete_local" && d.action !== "delete_remote"
    );
    const CONCURRENCY = 3;
    let fileOpIndex = 0;
    let completedOpsSinceSave = 0;
    const worker = async () => {
      while (fileOpIndex < fileOperations.length) {
        const d = fileOperations[fileOpIndex++];
        try {
          await this.executeFileOperation(d);
          syncedCount++;
          completedOpsSinceSave++;
          if (completedOpsSinceSave >= 5) {
            completedOpsSinceSave = 0;
            await this.db.save();
          }
          onProgress?.(
            syncedCount,
            totalCount,
            `Synced: ${d.key}`,
            d.key
          );
        } catch (err) {
          errors.push({ key: d.key, error: err.message || String(err) });
        }
      }
    };
    const workers = Array.from({ length: CONCURRENCY }, () => worker());
    await Promise.all(workers);
    await this.db.save();
    const fileDeletions = activeChanges.filter(
      (d) => !d.isFolder && (d.action === "delete_local" || d.action === "delete_remote")
    );
    for (const d of fileDeletions) {
      try {
        if (d.action === "delete_local") {
          await this.localFs.deleteFile(d.key);
        } else if (d.action === "delete_remote") {
          await this.driveApi.rm(d.key);
        }
        this.db.deleteRecord(d.key);
        syncedCount++;
        onProgress?.(syncedCount, totalCount, `Deleted: ${d.key}`, d.key);
      } catch (err) {
        errors.push({ key: d.key, error: err.message || String(err) });
      }
    }
    if (fileDeletions.length > 0) {
      await this.db.save();
    }
    const folderDeletions = activeChanges.filter(
      (d) => d.isFolder && (d.action === "delete_local_folder" || d.action === "delete_remote_folder")
    );
    folderDeletions.sort((a, b) => b.key.length - a.key.length);
    for (const d of folderDeletions) {
      try {
        let deleted = false;
        if (d.action === "delete_local_folder") {
          deleted = await this.localFs.deleteFolder(d.key);
        } else if (d.action === "delete_remote_folder") {
          deleted = await this.driveApi.rm(d.key);
        }
        if (deleted) {
          this.db.deleteRecord(d.key);
          syncedCount++;
          onProgress?.(syncedCount, totalCount, `Deleted folder: ${d.key}`, d.key);
        } else {
          console.warn(
            `Folder "${d.key}" was not deleted because it is not empty.`
          );
        }
      } catch (err) {
        errors.push({ key: d.key, error: err.message || String(err) });
      }
    }
    for (const d of decisions) {
      if (d.action === "skip" && !d.localEntity && !d.remoteEntity) {
        this.db.deleteRecord(d.key);
      }
    }
    await this.db.save();
    return { syncedCount, errors };
  }
  /**
   * Uploads a file with mid-upload modification guard (Typing-during-upload bug fix)
   */
  async uploadFileWithGuard(key, forcedMtime) {
    const now = Date.now();
    const statBefore = await this.localFs.stat(key);
    if (!statBefore) {
      return false;
    }
    const content = await this.localFs.readFile(key);
    const mtimeToUse = forcedMtime ?? statBefore.mtime;
    const uploaded = await this.driveApi.writeFile(key, content, mtimeToUse);
    const statAfter = await this.localFs.stat(key);
    const changedMidUpload = !statAfter || statAfter.mtime !== statBefore.mtime || statAfter.size !== statBefore.size;
    if (changedMidUpload) {
      console.warn(
        `File "${key}" was modified during upload. Recording pre-upload snapshot so next sync uploads the mid-upload edit.`
      );
      this.db.upsertRecord({
        key,
        isFolder: false,
        localSize: statBefore.size,
        localMtime: statBefore.mtime,
        remoteHash: uploaded.hash,
        remoteMtime: uploaded.mtime,
        remoteSize: uploaded.size,
        syncTime: now
      });
      return false;
    }
    this.db.upsertRecord({
      key,
      isFolder: false,
      localSize: statBefore.size,
      localMtime: statBefore.mtime,
      remoteHash: uploaded.hash,
      remoteMtime: uploaded.mtime,
      remoteSize: uploaded.size,
      syncTime: now
    });
    return true;
  }
  /**
   * Downloads a file with mid-sync local modification guard
   */
  async downloadFileWithGuard(d) {
    const now = Date.now();
    const statCurrent = await this.localFs.stat(d.key);
    const localModifiedMidSync = statCurrent && d.localEntity && (statCurrent.mtime !== d.localEntity.mtime || statCurrent.size !== d.localEntity.size);
    const localCreatedMidSync = statCurrent && !d.localEntity;
    if (localModifiedMidSync || localCreatedMidSync) {
      console.warn(
        `Local file "${d.key}" changed during sync download. Creating conflict copy.`
      );
      const remoteContent = await this.driveApi.readFile(d.key);
      const conflictKey = this.generateConflictPath(d.key);
      await this.localFs.writeFile(conflictKey, remoteContent);
      const conflictStat = await this.localFs.stat(conflictKey);
      this.db.upsertRecord({
        key: conflictKey,
        isFolder: false,
        localSize: remoteContent.byteLength,
        localMtime: conflictStat?.mtime ?? now,
        remoteHash: d.remoteEntity?.hash,
        remoteMtime: d.remoteEntity?.mtime,
        remoteSize: d.remoteEntity?.size ?? remoteContent.byteLength,
        syncTime: now
      });
      const uploadedConflict = await this.driveApi.writeFile(
        conflictKey,
        remoteContent,
        d.remoteEntity?.mtime
      );
      this.db.upsertRecord({
        key: conflictKey,
        isFolder: false,
        localSize: remoteContent.byteLength,
        localMtime: conflictStat?.mtime ?? now,
        remoteHash: uploadedConflict.hash,
        remoteMtime: uploadedConflict.mtime,
        remoteSize: uploadedConflict.size,
        syncTime: now
      });
      return;
    }
    const content = await this.driveApi.readFile(d.key);
    await this.localFs.writeFile(d.key, content);
    const localStat = await this.localFs.stat(d.key);
    this.db.upsertRecord({
      key: d.key,
      isFolder: false,
      localSize: content.byteLength,
      localMtime: localStat?.mtime ?? now,
      remoteHash: d.remoteEntity?.hash,
      remoteMtime: d.remoteEntity?.mtime,
      remoteSize: d.remoteEntity?.size ?? content.byteLength,
      syncTime: now
    });
  }
  async executeFileOperation(d) {
    const now = Date.now();
    switch (d.action) {
      case "upload":
      case "conflict_keep_local": {
        await this.uploadFileWithGuard(d.key, d.localEntity?.mtime);
        break;
      }
      case "download":
      case "conflict_keep_remote": {
        await this.downloadFileWithGuard(d);
        break;
      }
      case "conflict_keep_newer": {
        if (d.localEntity && d.remoteEntity && d.localEntity.mtime >= d.remoteEntity.mtime) {
          await this.uploadFileWithGuard(d.key, d.localEntity.mtime);
        } else {
          await this.downloadFileWithGuard(d);
        }
        break;
      }
      case "conflict_create_copy": {
        const remoteContent = await this.driveApi.readFile(d.key);
        const conflictKey = this.generateConflictPath(d.key);
        await this.localFs.writeFile(conflictKey, remoteContent);
        const conflictStat = await this.localFs.stat(conflictKey);
        await this.uploadFileWithGuard(d.key, d.localEntity?.mtime);
        const uploadedConflict = await this.driveApi.writeFile(
          conflictKey,
          remoteContent,
          d.remoteEntity?.mtime
        );
        this.db.upsertRecord({
          key: conflictKey,
          isFolder: false,
          localSize: remoteContent.byteLength,
          localMtime: conflictStat?.mtime ?? now,
          remoteHash: uploadedConflict.hash,
          remoteMtime: uploadedConflict.mtime,
          remoteSize: uploadedConflict.size,
          syncTime: now
        });
        break;
      }
      case "equal": {
        if (d.localEntity) {
          this.db.upsertRecord({
            key: d.key,
            isFolder: false,
            localSize: d.localEntity.size,
            localMtime: d.localEntity.mtime,
            remoteHash: d.remoteEntity?.hash,
            remoteMtime: d.remoteEntity?.mtime,
            remoteSize: d.remoteEntity?.size,
            syncTime: now
          });
        }
        break;
      }
    }
  }
  generateConflictPath(originalKey) {
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-").replace("T", "_").slice(0, 19);
    const lastDot = originalKey.lastIndexOf(".");
    if (lastDot > 0 && lastDot > originalKey.lastIndexOf("/")) {
      const base = originalKey.substring(0, lastDot);
      const ext = originalKey.substring(lastDot);
      return `${base}.sync-conflict-${timestamp}${ext}`;
    }
    return `${originalKey}.sync-conflict-${timestamp}`;
  }
  checkSafetyGuard(decisions) {
    const threshold = this.settings.protectModifyDeletePercentage;
    if (threshold <= 0 || threshold >= 100) {
      return;
    }
    const deletionCount = decisions.filter(
      (d) => d.action === "delete_local" || d.action === "delete_remote" || d.action === "delete_local_folder" || d.action === "delete_remote_folder"
    ).length;
    const totalTracked = this.db.count;
    if (totalTracked < 10) {
      return;
    }
    const percent = deletionCount / totalTracked * 100;
    if (percent > threshold) {
      throw new Error(
        `Safety Guard Abort: This sync run would delete ${deletionCount} items (${percent.toFixed(
          1
        )}% of your vault), which exceeds your safety limit of ${threshold}%. Please check your settings or manually verify.`
      );
    }
  }
};

// src/settingsTab.ts
var import_obsidian4 = require("obsidian");

// src/oauthDeviceFlow.ts
var import_obsidian3 = require("obsidian");
var GoogleOAuthDeviceFlow = class {
  /**
   * Initiates the OAuth 2.0 Device Code Flow
   */
  static async requestDeviceCode(clientId, scope) {
    if (!clientId) {
      throw new Error("Missing Google Client ID. Please configure it in plugin settings.");
    }
    const params = new URLSearchParams({
      client_id: clientId,
      scope
    });
    if (scope === "https://www.googleapis.com/auth/drive") {
      throw new Error(
        "Google's Device Flow restricts full drive access. Please switch scope to 'App-Created Files Only' in settings, or use 'Manual Token Entry' if syncing an existing drive folder."
      );
    }
    try {
      const resp = await (0, import_obsidian3.requestUrl)({
        url: "https://oauth2.googleapis.com/device/code",
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: params.toString()
      });
      if (resp.status !== 200) {
        throw new Error(
          `Failed to obtain device code from Google: ${GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`
        );
      }
      return resp.json;
    } catch (err) {
      if (err.status === 400 || err.message && err.message.includes("400")) {
        throw new Error(
          "Google Device Flow rejected the request (Status 400). Ensure your Google Client ID is of type 'TVs and Limited Input devices' and scope is set to 'App-Created Files Only'."
        );
      }
      throw err;
    }
  }
  /**
   * Polls Google token endpoint until user approves or denies
   */
  static async pollForTokens(clientId, clientSecret, deviceCode, intervalSeconds, expiresInSeconds, isCancelled, onStatusUpdate) {
    if (!clientSecret) {
      throw new Error("Missing Google Client Secret. Google requires client_secret for device code authentication.");
    }
    const deadline = Date.now() + expiresInSeconds * 1e3;
    let pollInterval = Math.max(intervalSeconds, 5);
    while (Date.now() < deadline) {
      if (isCancelled()) {
        throw new Error("Authorization was cancelled.");
      }
      await new Promise((resolve) => setTimeout(resolve, pollInterval * 1e3));
      if (isCancelled()) {
        throw new Error("Authorization was cancelled.");
      }
      const params = new URLSearchParams({
        client_id: clientId,
        device_code: deviceCode,
        grant_type: "urn:ietf:params:oauth:grant-type:device_code"
      });
      if (clientSecret) {
        params.append("client_secret", clientSecret);
      }
      try {
        const resp = await (0, import_obsidian3.requestUrl)({
          url: "https://oauth2.googleapis.com/token",
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded"
          },
          body: params.toString(),
          throw: false
        });
        if (resp.status === 200) {
          const data = resp.json;
          return {
            accessToken: data.access_token,
            refreshToken: data.refresh_token,
            expiresIn: Number(data.expires_in) || 3600
          };
        }
        const errJson = resp.json || {};
        const error = errJson.error;
        if (error === "authorization_pending") {
          onStatusUpdate?.("Waiting for approval in browser...");
          continue;
        } else if (error === "slow_down") {
          pollInterval += 5;
          onStatusUpdate?.("Waiting (rate-adjusted)...");
          continue;
        } else if (error === "access_denied") {
          throw new Error("Access was denied on the Google consent screen.");
        } else if (error === "expired_token") {
          throw new Error("The authorization session timed out. Please try again.");
        } else {
          throw new Error(`Token authorization error: ${GoogleDriveApi.formatGoogleError(resp.text, resp.status)}`);
        }
      } catch (err) {
        if (err.message?.includes("denied") || err.message?.includes("timed out") || err.message?.includes("cancelled")) {
          throw err;
        }
        console.warn("Polling request blip:", err);
      }
    }
    throw new Error("Authorization timed out.");
  }
};
var DeviceAuthModal = class extends import_obsidian3.Modal {
  constructor(app, deviceResponse, clientId, clientSecret, onSuccess) {
    super(app);
    this.cancelled = false;
    this.deviceResponse = deviceResponse;
    this.clientId = clientId;
    this.clientSecret = clientSecret;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("gdrive-auth-modal");
    contentEl.createEl("h2", {
      text: "Connect Google Drive",
      cls: "gdrive-auth-modal-header"
    });
    const stepBox = contentEl.createDiv({ cls: "gdrive-auth-step-box" });
    stepBox.createEl("p", {
      text: "1. Copy this one-time code:"
    });
    const codeBox = stepBox.createDiv({ cls: "gdrive-auth-code-container" });
    codeBox.createDiv({
      text: this.deviceResponse.user_code,
      cls: "gdrive-auth-user-code"
    });
    const copyBtn = codeBox.createEl("button", {
      text: "Copy Code"
    });
    copyBtn.onclick = async () => {
      await navigator.clipboard.writeText(this.deviceResponse.user_code);
      new import_obsidian3.Notice("Code copied to clipboard!");
    };
    stepBox.createEl("p", {
      text: "2. Open Google in your browser, paste the code, and grant permission:"
    });
    const verifyUrl = this.deviceResponse.verification_url || "https://www.google.com/device";
    const directUrl = `${verifyUrl}?user_code=${encodeURIComponent(
      this.deviceResponse.user_code
    )}`;
    const btnRow = stepBox.createDiv({ cls: "gdrive-auth-button-row" });
    const openBtn = btnRow.createEl("button", {
      text: "Open Google Login in Browser",
      cls: "mod-cta"
    });
    openBtn.onclick = () => {
      window.open(directUrl, "_blank");
    };
    const cancelBtn = btnRow.createEl("button", {
      text: "Cancel"
    });
    cancelBtn.onclick = () => {
      this.cancelled = true;
      this.close();
    };
    this.statusEl = contentEl.createDiv({ cls: "gdrive-auth-polling-status" });
    this.statusEl.createDiv({ cls: "gdrive-auth-spinner" });
    const statusText = this.statusEl.createSpan({
      text: "Waiting for approval in browser..."
    });
    this.startPolling(statusText);
  }
  async startPolling(statusTextSpan) {
    try {
      const result = await GoogleOAuthDeviceFlow.pollForTokens(
        this.clientId,
        this.clientSecret,
        this.deviceResponse.device_code,
        this.deviceResponse.interval,
        this.deviceResponse.expires_in,
        () => this.cancelled,
        (text) => {
          statusTextSpan.setText(text);
        }
      );
      if (this.cancelled)
        return;
      new import_obsidian3.Notice("Google Drive connected successfully!");
      await this.onSuccess(result);
      this.close();
    } catch (err) {
      if (!this.cancelled) {
        new import_obsidian3.Notice(`Login failed: ${err.message}`);
        this.close();
      }
    }
  }
  onClose() {
    this.cancelled = true;
    this.contentEl.empty();
  }
};

// src/settingsTab.ts
var GDriveSyncSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Google Drive Sync Settings" });
    this.renderAccountSection(containerEl);
    this.renderRemoteTargetSection(containerEl);
    this.renderAutomationSection(containerEl);
    this.renderConflictAndSafetySection(containerEl);
    this.renderExclusionsSection(containerEl);
    this.renderDiagnosticsSection(containerEl);
  }
  renderAccountSection(containerEl) {
    containerEl.createEl("h3", { text: "Google Account" });
    const isConnected = !!this.plugin.settings.googleDrive.refreshToken;
    const card = containerEl.createDiv({ cls: "gdrive-settings-card" });
    const infoRow = card.createDiv({ cls: "gdrive-account-info" });
    const badge = infoRow.createSpan({
      cls: `gdrive-status-badge ${isConnected ? "connected" : "disconnected"}`,
      text: isConnected ? "Connected" : "Not Connected"
    });
    if (isConnected && this.plugin.settings.googleDrive.userEmail) {
      infoRow.createSpan({
        cls: "gdrive-account-email",
        text: this.plugin.settings.googleDrive.userEmail
      });
    }
    if (isConnected) {
      new import_obsidian4.Setting(card).setName("Check Connection").setDesc("Test authentication and Google Drive API connectivity").addButton((btn) => {
        btn.setButtonText("Test Connection").onClick(async () => {
          btn.setDisabled(true);
          try {
            const userInfo = await this.plugin.driveApi.getUserInfo();
            this.plugin.settings.googleDrive.userEmail = userInfo.email;
            this.plugin.settings.googleDrive.userDisplayName = userInfo.name;
            await this.plugin.saveSettings();
            new import_obsidian4.Notice(`Connected to Google Drive as ${userInfo.email}`);
            this.display();
          } catch (err) {
            new import_obsidian4.Notice(`Connection test failed: ${err.message}`);
          } finally {
            btn.setDisabled(false);
          }
        });
      }).addButton((btn) => {
        btn.setButtonText("Disconnect Account").setWarning().onClick(async () => {
          this.plugin.settings.googleDrive.refreshToken = "";
          this.plugin.settings.googleDrive.accessToken = "";
          this.plugin.settings.googleDrive.accessTokenExpiresAtMs = 0;
          this.plugin.settings.googleDrive.userEmail = "";
          this.plugin.settings.googleDrive.userDisplayName = "";
          await this.plugin.saveSettings();
          new import_obsidian4.Notice("Google Drive disconnected.");
          this.display();
        });
      });
    } else {
      new import_obsidian4.Setting(card).setName("Google OAuth Credentials").setDesc(
        "Enter your Google Cloud OAuth 2.0 Client ID and Secret (type: 'TVs and Limited Input devices')."
      );
      new import_obsidian4.Setting(card).setName("Google Client ID").setDesc("Client ID from your Google Cloud Console project").addText((text) => {
        text.setPlaceholder("e.g. 123456789-abcdef.apps.googleusercontent.com").setValue(this.plugin.settings.googleDrive.clientId).onChange(async (val) => {
          this.plugin.settings.googleDrive.clientId = val.trim();
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian4.Setting(card).setName("Google Client Secret").setDesc("Required by Google OAuth 2.0 Device Flow").addText((text) => {
        text.setPlaceholder("GOCSPX-...").setValue(this.plugin.settings.googleDrive.clientSecret).onChange(async (val) => {
          this.plugin.settings.googleDrive.clientSecret = val.trim();
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian4.Setting(card).setName("Google Drive OAuth Scope").setDesc(
        "For Google Device Login, select 'App-Created Files Only' (Google blocks full drive scope on device flow). To sync an existing Drive folder with Full Access, use 'Manual Token Entry' below."
      ).addDropdown((drop) => {
        drop.addOption(
          "https://www.googleapis.com/auth/drive.file",
          "App-Created Files Only (Required for Device Flow)"
        ).addOption(
          "https://www.googleapis.com/auth/drive",
          "Full Drive Access (Manual Token Entry only)"
        ).setValue(
          this.plugin.settings.googleDrive.scope || "https://www.googleapis.com/auth/drive.file"
        ).onChange(async (val) => {
          this.plugin.settings.googleDrive.scope = val;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian4.Setting(card).setName("Connect to Google Drive").setDesc(
        "Authorize this plugin to access your vault files using Google's secure device login"
      ).addButton((btn) => {
        btn.setButtonText("Connect Account").setCta().onClick(async () => {
          const { clientId, clientSecret, scope } = this.plugin.settings.googleDrive;
          if (!clientId || !clientSecret) {
            new import_obsidian4.Notice(
              "Please enter both your Google Client ID and Client Secret before connecting."
            );
            return;
          }
          btn.setDisabled(true);
          try {
            const deviceResp = await GoogleOAuthDeviceFlow.requestDeviceCode(
              clientId,
              scope
            );
            new DeviceAuthModal(
              this.app,
              deviceResp,
              clientId,
              clientSecret,
              async (tokens) => {
                this.plugin.settings.googleDrive.refreshToken = tokens.refreshToken;
                this.plugin.settings.googleDrive.accessToken = tokens.accessToken;
                this.plugin.settings.googleDrive.accessTokenExpiresAtMs = Date.now() + tokens.expiresIn * 1e3;
                try {
                  const userInfo = await this.plugin.driveApi.getUserInfo();
                  this.plugin.settings.googleDrive.userEmail = userInfo.email;
                  this.plugin.settings.googleDrive.userDisplayName = userInfo.name;
                } catch (e) {
                  console.warn("Could not fetch user details right away", e);
                }
                await this.plugin.saveSettings();
                this.display();
              }
            ).open();
          } catch (err) {
            new import_obsidian4.Notice(`Auth error: ${err.message}`);
          } finally {
            btn.setDisabled(false);
          }
        });
      });
    }
    const advancedDetails = containerEl.createEl("details");
    advancedDetails.createEl("summary", {
      text: "Manual Token Entry (Alternative)"
    });
    new import_obsidian4.Setting(advancedDetails).setName("Manual Refresh Token").setDesc("Paste an existing Google OAuth refresh token directly").addText((text) => {
      text.setPlaceholder("1//...").setValue(this.plugin.settings.googleDrive.refreshToken).onChange(async (val) => {
        this.plugin.settings.googleDrive.refreshToken = val.trim();
        this.plugin.settings.googleDrive.accessToken = "";
        this.plugin.settings.googleDrive.accessTokenExpiresAtMs = 0;
        await this.plugin.saveSettings();
      });
    });
  }
  renderRemoteTargetSection(containerEl) {
    containerEl.createEl("h3", { text: "Vault Storage Location" });
    new import_obsidian4.Setting(containerEl).setName("Remote Vault Directory").setDesc(
      "Folder on Google Drive where notes will be stored (e.g. 'Obsidian/MyVault'). Defaults to your vault name if left empty."
    ).addText((text) => {
      text.setPlaceholder(this.app.vault.getName()).setValue(this.plugin.settings.remoteVaultDir).onChange(async (val) => {
        this.plugin.settings.remoteVaultDir = val.trim();
        this.plugin.driveApi.updateConfig(
          this.plugin.settings.googleDrive,
          this.plugin.settings.remoteVaultDir
        );
        await this.plugin.saveSettings();
      });
    });
  }
  renderAutomationSection(containerEl) {
    containerEl.createEl("h3", { text: "Sync Automation" });
    new import_obsidian4.Setting(containerEl).setName("Sync on Startup").setDesc("Automatically sync when Obsidian opens (recommended for mobile)").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (val) => {
        this.plugin.settings.syncOnStartup = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Periodic Sync").setDesc("Automatically sync in the background at regular intervals").addDropdown((drop) => {
      drop.addOption("0", "Disabled").addOption("5", "Every 5 minutes").addOption("10", "Every 10 minutes").addOption("15", "Every 15 minutes").addOption("30", "Every 30 minutes").addOption("60", "Every 1 hour").setValue(String(this.plugin.settings.periodicSyncIntervalMinutes)).onChange(async (val) => {
        this.plugin.settings.periodicSyncIntervalMinutes = Number(val);
        await this.plugin.saveSettings();
        this.plugin.setupPeriodicTimer();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Sync on File Change").setDesc("Automatically sync shortly after you modify or create a note").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.syncOnSave).onChange(async (val) => {
        this.plugin.settings.syncOnSave = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("File Change Delay (seconds)").setDesc("Wait time after your last edit before triggering sync").addSlider((slider) => {
      slider.setLimits(3, 60, 1).setValue(this.plugin.settings.syncOnSaveDelaySeconds).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.syncOnSaveDelaySeconds = val;
        await this.plugin.saveSettings();
      });
    });
  }
  renderConflictAndSafetySection(containerEl) {
    containerEl.createEl("h3", { text: "Conflicts & Safety Guard" });
    new import_obsidian4.Setting(containerEl).setName("Sync Direction").setDesc("Choose whether sync is bidirectional or one-way").addDropdown((drop) => {
      drop.addOption("bidirectional", "Bidirectional (Two-way)").addOption("push_only", "Push Only (Local to Google Drive)").addOption("pull_only", "Pull Only (Google Drive to Local)").setValue(this.plugin.settings.syncDirection).onChange(async (val) => {
        this.plugin.settings.syncDirection = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Conflict Resolution").setDesc("How to resolve when both local and Google Drive files were modified").addDropdown((drop) => {
      drop.addOption("keep_newer", "Keep Newer File (by modification time)").addOption("keep_local", "Always Keep Local").addOption("keep_remote", "Always Keep Remote").addOption(
        "create_conflict_copy",
        "Keep Both (Create .sync-conflict- copy)"
      ).setValue(this.plugin.settings.conflictAction).onChange(async (val) => {
        this.plugin.settings.conflictAction = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Accidental Deletion Protection Threshold (%)").setDesc(
      "Halts sync if more than this percentage of files would be deleted in a single run (prevents catastrophic loss). Set to 0 to disable."
    ).addSlider((slider) => {
      slider.setLimits(0, 100, 5).setValue(this.plugin.settings.protectModifyDeletePercentage).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.protectModifyDeletePercentage = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Sync .obsidian Configuration Folder").setDesc(
      "Sync plugin configurations, snippets, and themes (excluding workspace cache). Caution: May conflict if devices have different screen sizes."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.syncConfigDir).onChange(async (val) => {
        this.plugin.settings.syncConfigDir = val;
        await this.plugin.saveSettings();
      });
    });
  }
  renderExclusionsSection(containerEl) {
    containerEl.createEl("h3", { text: "Exclusions" });
    new import_obsidian4.Setting(containerEl).setName("Ignored Patterns (RegExp)").setDesc(
      "One regular expression per line. Files or folders matching these patterns will be excluded from sync."
    ).addTextArea((text) => {
      text.setPlaceholder("^\\.git/\n\\.DS_Store$").setValue(this.plugin.settings.ignoredPatterns.join("\n")).onChange(async (val) => {
        this.plugin.settings.ignoredPatterns = val.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 5;
      text.inputEl.cols = 35;
    });
  }
  renderDiagnosticsSection(containerEl) {
    containerEl.createEl("h3", { text: "Diagnostics & Actions" });
    new import_obsidian4.Setting(containerEl).setName("Sync Now").setDesc("Trigger an immediate manual synchronization run").addButton((btn) => {
      btn.setButtonText("Sync Now").setCta().onClick(async () => {
        await this.plugin.triggerSync("manual");
        this.display();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Reset Local Sync Cache").setDesc(
      "Clears the local sync database. Use if you want the plugin to re-scan all local and remote files afresh."
    ).addButton((btn) => {
      btn.setButtonText("Reset Cache").setWarning().onClick(async () => {
        this.plugin.db.clear();
        await this.plugin.db.save();
        new import_obsidian4.Notice("Local sync cache cleared.");
      });
    });
    if (this.plugin.settings.lastSyncTime > 0) {
      const timeStr = new Date(
        this.plugin.settings.lastSyncTime
      ).toLocaleString();
      const statusText = `Status: ${this.plugin.settings.lastSyncStatus.toUpperCase()} | Last Run: ${timeStr}`;
      const logBox = containerEl.createDiv({ cls: "gdrive-sync-log-box" });
      logBox.createEl("div", { text: statusText });
      if (this.plugin.settings.lastSyncError) {
        logBox.createEl("div", {
          text: `Error: ${this.plugin.settings.lastSyncError}`,
          cls: "text-error"
        });
      }
    }
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  googleDrive: {
    clientId: "",
    clientSecret: "",
    refreshToken: "",
    accessToken: "",
    accessTokenExpiresAtMs: 0,
    scope: "https://www.googleapis.com/auth/drive.file"
  },
  remoteVaultDir: "",
  syncDirection: "bidirectional",
  conflictAction: "create_conflict_copy",
  syncOnStartup: true,
  periodicSyncIntervalMinutes: 10,
  syncOnSave: false,
  syncOnSaveDelaySeconds: 5,
  syncConfigDir: false,
  protectModifyDeletePercentage: 25,
  ignoredPatterns: [
    "^\\.git/",
    "^\\.trash/",
    "^\\.obsidian/workspace(\\.json)?",
    "\\.DS_Store$",
    "^desktop\\.ini$",
    "thumbs\\.db$",
    "~\\$"
  ],
  lastSyncTime: 0,
  lastSyncStatus: "idle",
  lastSyncError: ""
};

// src/main.ts
var GDriveSyncPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.isSyncing = false;
    this.syncRibbonEl = null;
    this.statusBarEl = null;
    this.periodicTimer = null;
    this.saveDebounceTimer = null;
    this.eventRefs = [];
  }
  async onload() {
    console.log("Loading Obsidian Google Drive Sync Plugin");
    await this.loadSettings();
    this.db = new LocalDb(this);
    await this.db.load();
    this.localFs = new FsLocal(
      this.app.vault,
      this.settings.syncConfigDir,
      this.settings.ignoredPatterns
    );
    this.driveApi = new GoogleDriveApi(
      this.settings.googleDrive,
      this.app.vault.getName(),
      this.settings.remoteVaultDir,
      async (updated) => {
        this.settings.googleDrive = updated;
        await this.saveSettings();
      }
    );
    this.syncEngine = new SyncEngine(
      this.localFs,
      this.driveApi,
      this.db,
      this.settings
    );
    this.addSettingTab(new GDriveSyncSettingTab(this.app, this));
    this.syncRibbonEl = this.addRibbonIcon(
      "refresh-cw",
      "Sync with Google Drive",
      () => {
        this.triggerSync("ribbon");
      }
    );
    this.syncRibbonEl.addClass("gdrive-sync-ribbon");
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarEl.addClass("gdrive-sync-status-bar");
    this.updateStatusBar("Idle");
    this.statusBarEl.onclick = () => {
      this.triggerSync("manual");
    };
    this.addCommand({
      id: "gdrive-sync-now",
      name: "Sync now with Google Drive",
      callback: () => this.triggerSync("manual")
    });
    this.addCommand({
      id: "gdrive-push-all",
      name: "Force Push to Google Drive (Upload all)",
      callback: () => this.triggerSync("manual", "push_only")
    });
    this.addCommand({
      id: "gdrive-pull-all",
      name: "Force Pull from Google Drive (Download all)",
      callback: () => this.triggerSync("manual", "pull_only")
    });
    this.addCommand({
      id: "gdrive-check-connection",
      name: "Check Google Drive Connection",
      callback: async () => {
        try {
          const user = await this.driveApi.getUserInfo();
          new import_obsidian5.Notice(`Google Drive is connected: ${user.email}`);
        } catch (err) {
          new import_obsidian5.Notice(`Google Drive connection error: ${err.message}`);
        }
      }
    });
    this.registerFileWatchers();
    this.setupPeriodicTimer();
    if (this.settings.syncOnStartup) {
      this.app.workspace.onLayoutReady(() => {
        window.setTimeout(() => {
          this.triggerSync("startup");
        }, 3e3);
      });
    }
  }
  onunload() {
    console.log("Unloading Obsidian Google Drive Sync Plugin");
    if (this.periodicTimer !== null) {
      window.clearInterval(this.periodicTimer);
      this.periodicTimer = null;
    }
    if (this.saveDebounceTimer !== null) {
      window.clearTimeout(this.saveDebounceTimer);
      this.saveDebounceTimer = null;
    }
    for (const ref of this.eventRefs) {
      this.app.vault.offref(ref);
    }
    this.eventRefs = [];
  }
  setupPeriodicTimer() {
    if (this.periodicTimer !== null) {
      window.clearInterval(this.periodicTimer);
      this.periodicTimer = null;
    }
    const minutes = this.settings.periodicSyncIntervalMinutes;
    if (minutes > 0) {
      this.periodicTimer = window.setInterval(() => {
        this.triggerSync("timer");
      }, minutes * 60 * 1e3);
    }
  }
  registerFileWatchers() {
    const onFileChange = (file) => {
      if (!this.settings.syncOnSave || this.isSyncing) {
        return;
      }
      if (this.localFs.isIgnored(file.path)) {
        return;
      }
      if (this.saveDebounceTimer !== null) {
        window.clearTimeout(this.saveDebounceTimer);
      }
      const delay = Math.max(this.settings.syncOnSaveDelaySeconds, 2) * 1e3;
      this.saveDebounceTimer = window.setTimeout(() => {
        this.triggerSync("save");
      }, delay);
    };
    this.eventRefs.push(this.app.vault.on("modify", onFileChange));
    this.eventRefs.push(this.app.vault.on("create", onFileChange));
    this.eventRefs.push(this.app.vault.on("delete", onFileChange));
    this.eventRefs.push(this.app.vault.on("rename", onFileChange));
  }
  async triggerSync(trigger, forcedDirection) {
    if (this.isSyncing) {
      new import_obsidian5.Notice("Google Drive sync is already in progress.");
      return;
    }
    if (!this.settings.googleDrive.refreshToken) {
      if (trigger === "manual" || trigger === "ribbon") {
        new import_obsidian5.Notice(
          "Google Drive is not connected. Please connect your account in Settings."
        );
      }
      return;
    }
    this.isSyncing = true;
    this.updateRibbonState("syncing");
    this.updateStatusBar("Syncing...");
    const effectiveSettings = { ...this.settings };
    if (forcedDirection) {
      effectiveSettings.syncDirection = forcedDirection;
    }
    const engine = new SyncEngine(
      this.localFs,
      this.driveApi,
      this.db,
      effectiveSettings
    );
    try {
      this.driveApi.clearCache();
      this.updateStatusBar("Scanning local...");
      const localEntities = await this.localFs.walk();
      this.updateStatusBar("Scanning Google Drive...");
      const remoteEntities = await this.driveApi.walk();
      this.updateStatusBar("Planning sync...");
      const decisions = await engine.planSync(localEntities, remoteEntities);
      const changeCount = decisions.filter((d) => d.isChange).length;
      if (changeCount === 0) {
        this.settings.lastSyncTime = Date.now();
        this.settings.lastSyncStatus = "success";
        this.settings.lastSyncError = "";
        await this.saveSettings();
        this.updateRibbonState("success");
        this.updateStatusBar("Up to date");
        if (trigger === "manual" || trigger === "ribbon") {
          new import_obsidian5.Notice("Google Drive: Vault is already up to date.");
        }
        return;
      }
      this.updateStatusBar(`Syncing (0/${changeCount})...`);
      const result = await engine.executePlan(
        decisions,
        (curr, total, msg) => {
          this.updateStatusBar(`Syncing (${curr}/${total})...`);
        }
      );
      this.settings.lastSyncTime = Date.now();
      this.settings.lastSyncStatus = "success";
      this.settings.lastSyncError = result.errors.length > 0 ? `${result.errors.length} errors occurred` : "";
      await this.saveSettings();
      this.updateRibbonState("success");
      this.updateStatusBar("Synced");
      if (result.errors.length > 0) {
        new import_obsidian5.Notice(
          `Sync completed with ${result.errors.length} errors. Check console for details.`
        );
        console.warn("Google Drive Sync errors:", result.errors);
      } else {
        new import_obsidian5.Notice(`Google Drive: Synced ${result.syncedCount} items.`);
      }
    } catch (err) {
      console.error("Google Drive sync failed:", err);
      const formatted = GoogleDriveApi.formatGoogleError(err.message || String(err));
      this.settings.lastSyncStatus = "error";
      this.settings.lastSyncError = formatted;
      await this.saveSettings();
      this.updateRibbonState("error");
      this.updateStatusBar("Sync Error");
      new import_obsidian5.Notice(`Google Drive Sync Error: ${formatted}`);
    } finally {
      this.isSyncing = false;
      window.setTimeout(() => {
        if (!this.isSyncing) {
          this.updateRibbonState("idle");
          this.formatLastSyncStatusBar();
        }
      }, 4e3);
    }
  }
  updateRibbonState(state) {
    if (!this.syncRibbonEl)
      return;
    this.syncRibbonEl.removeClass("is-syncing");
    this.syncRibbonEl.removeClass("sync-success");
    this.syncRibbonEl.removeClass("sync-error");
    if (state === "syncing") {
      this.syncRibbonEl.addClass("is-syncing");
    } else if (state === "success") {
      this.syncRibbonEl.addClass("sync-success");
    } else if (state === "error") {
      this.syncRibbonEl.addClass("sync-error");
    }
  }
  updateStatusBar(text) {
    if (!this.statusBarEl)
      return;
    this.statusBarEl.setText(`GDrive: ${text}`);
  }
  formatLastSyncStatusBar() {
    if (this.settings.lastSyncTime > 0) {
      const minsAgo = Math.round(
        (Date.now() - this.settings.lastSyncTime) / 6e4
      );
      if (minsAgo < 1) {
        this.updateStatusBar("Just now");
      } else if (minsAgo < 60) {
        this.updateStatusBar(`${minsAgo}m ago`);
      } else {
        const hoursAgo = Math.round(minsAgo / 60);
        this.updateStatusBar(`${hoursAgo}h ago`);
      }
    } else {
      this.updateStatusBar("Idle");
    }
  }
  async loadSettings() {
    const data = await this.loadData() || {};
    const { syncRecords, ...settingsData } = data;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, settingsData);
    if (settingsData && settingsData.googleDrive) {
      this.settings.googleDrive = Object.assign(
        {},
        DEFAULT_SETTINGS.googleDrive,
        settingsData.googleDrive
      );
    }
  }
  async saveSettings() {
    const currentData = await this.loadData() || {};
    const activeSyncRecords = currentData.syncRecords;
    const settingsCopy = { ...this.settings };
    delete settingsCopy.syncRecords;
    const toSave = Object.assign({}, currentData, settingsCopy);
    if (activeSyncRecords !== void 0) {
      toSave.syncRecords = activeSyncRecords;
    } else {
      delete toSave.syncRecords;
    }
    await this.saveData(toSave);
  }
};
var main_default = GDriveSyncPlugin;
